package waf

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	appsettings "github.com/0xJacky/Nginx-UI/settings"
)

func boolLiteral(value bool) string {
	if value {
		return "true"
	}
	return "false"
}

func Normalize(settings appsettings.WAF) appsettings.WAF {
	isZero := settings == appsettings.WAF{}
	settings.Mode = strings.ToUpper(strings.TrimSpace(settings.Mode))
	settings = settings.WithDefaults()
	if isZero {
		settings.EventLogAlteredOnly = true
	}
	return settings
}

func RenderRuntimeConfig(settings appsettings.WAF) string {
	settings = Normalize(settings)
	return fmt.Sprintf(`-- Generated by Nginx UI. Do not edit manually.
return {
    enabled = %s,
    mode = %q,
    score_threshold = %d,
    deny_status = %d,
    debug = %s,
    event_log_altered_only = %s,
}
`,
		boolLiteral(settings.Enabled),
		settings.Mode,
		settings.ScoreThreshold,
		settings.DenyStatus,
		boolLiteral(settings.Debug),
		boolLiteral(settings.EventLogAlteredOnly),
	)
}

func RuntimeConfigPath(settings appsettings.WAF) string {
	settings = Normalize(settings)
	return settings.ConfigPath
}

func WriteRuntimeConfig(settings appsettings.WAF) error {
	settings = Normalize(settings)
	path := RuntimeConfigPath(settings)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	tmpPath := path + ".tmp"
	if err := os.WriteFile(tmpPath, []byte(RenderRuntimeConfig(settings)), 0o644); err != nil {
		return err
	}
	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return err
	}
	return os.Chmod(path, 0o644)
}
