package waf

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	appsettings "github.com/0xJacky/Nginx-UI/settings"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRenderRuntimeConfigNormalizesAndEscapesSettings(t *testing.T) {
	cfg := RenderRuntimeConfig(appsettings.WAF{
		Enabled:             true,
		Mode:                "active",
		ScoreThreshold:      7,
		DenyStatus:          406,
		Debug:               true,
		EventLogAlteredOnly: false,
	})

	assert.Contains(t, cfg, "enabled = true")
	assert.Contains(t, cfg, "mode = \"ACTIVE\"")
	assert.Contains(t, cfg, "score_threshold = 7")
	assert.Contains(t, cfg, "deny_status = 406")
	assert.Contains(t, cfg, "debug = true")
	assert.Contains(t, cfg, "event_log_altered_only = false")
}

func TestRenderRuntimeConfigAppliesSafeDefaults(t *testing.T) {
	cfg := RenderRuntimeConfig(appsettings.WAF{})

	assert.Contains(t, cfg, "enabled = false")
	assert.Contains(t, cfg, "mode = \"SIMULATE\"")
	assert.Contains(t, cfg, "score_threshold = 5")
	assert.Contains(t, cfg, "deny_status = 403")
	assert.Contains(t, cfg, "debug = false")
	assert.Contains(t, cfg, "event_log_altered_only = true")
}

func TestWriteRuntimeConfigCreatesReadableLuaSettingsFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "nested", "settings.lua")

	err := WriteRuntimeConfig(appsettings.WAF{
		Enabled:             true,
		Mode:                "ACTIVE",
		ScoreThreshold:      9,
		DenyStatus:          451,
		EventLogAlteredOnly: true,
		ConfigPath:          path,
	})
	require.NoError(t, err)

	content, err := os.ReadFile(path)
	require.NoError(t, err)

	assert.True(t, strings.HasPrefix(string(content), "-- Generated by Nginx UI"))
	assert.Contains(t, string(content), "mode = \"ACTIVE\"")
	info, err := os.Stat(path)
	require.NoError(t, err)
	assert.Equal(t, os.FileMode(0o644), info.Mode().Perm())
}
